### ISSUE TITLE
Notification Service Extension

### ISSUE THREAD

**Issue by luicm** [AppoxeeMobile/iosArtifacts#1]
Hi, 
I have an app that mix objective-c and still Swift 2.3
I have installed the SDK 4.1 and i'm trying to use it with Notification Service Extension but I'm getting no results. 
Also, although I am getting the push notifications, the method : `-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo` is not being call anymore. 

Is there something I'm missing to implement?

**Comment by razelkayamdev** [comment]
Hi, 
1. In order for the extension to start executing your code, the notification payload needs to contain the `mutable-content = 1` key. 
2. If you are running on iOS10, then the delegate methods of `UserNotificationCenter` are the methods which handle the push payload. If you are choosing to become the delegate your self, you will need to forward its call to Appoxee. Have a look here: https://developer.apple.com/reference/foundation/nsusernotificationcenterdelegate
